### ISSUE TITLE
Zabbix 3.0+ needs additional config

### ISSUE THREAD

**Issue by damaarten** [ericoc/zabbix-slack-alertscript#10]
Zabbix 3.0+ needs additional config.
See screen shot below.
To add this to the README.mnd, you could insert the following on line 64:

"On Zabbix 3.0+, you also need to specify 3 script parameters, like so:

![Zabbix 3.0+ Media Type](https://cloud.githubusercontent.com/assets/4435822/13886511/80aa0c26-ed37-11e5-881b-f77e95bc5561.png "Zabbix 3.0+ Media Type")
"

**Comment by damaarten** [comment]
![zabbix-3 0-slack-settings](https://cloud.githubusercontent.com/assets/4435822/13886511/80aa0c26-ed37-11e5-881b-f77e95bc5561.png)

**Comment by tkdywc** [comment]
Hi damaarten,

It still doesn't work for me even adding the Macro. No message will be received in Slack completely with the above Macro added. Do you have any idea about it?

BR,

Yung

**Comment by devlinrcg** [comment]
Done on https://github.com/ericoc/zabbix-slack-alertscript/pull/12

**Comment by ericoc** [comment]
Thank you all for reporting and investigating this - much appreciated! I've updated the README per https://github.com/ericoc/zabbix-slack-alertscript/commit/0c3347d74d5c480bbc061e29ce89d6b43423599a to close this out - cheers!
