### ISSUE TITLE
Suggestion for the emoji config

### ISSUE THREAD

**Issue by dmz006** [ericoc/zabbix-slack-alertscript#13]
My subjects say a bit more than just RECOVERY / PROBLEM, but they are embedded into the subject string.  I suggest changing the if statement to be something like:

if [[ "$subject" =~ "RECOVERY" ]]; then
	emoji=':smile:'
if [[ "$subject" =~ "RECOVERED" ]]; then
	emoji=':smile:'
elif [[ "$subject" =~ "PROBLEM" ]]; then
	emoji=':frowning:'
else
	emoji=':ghost:'
fi

I have some that say recovered vs recovery which is why I have the extra line but this uses an extended regular expression search (=~) which will match better than a simple equals (==)

Let me know if you'd prefer that I pull & submit a change that way.

**Comment by Devorkin** [comment]
@dmz006 Your second IF statement has a small mistake, it should be elif instead of if :)
@ericoc Please note that your IF statement section ain't working (At least for me) the code is missing the double [[ ]] signs.

**Comment by dmz006** [comment]
Yeah I caught the elif right after posting,  I think the brackets were git hub stripped off from the post,  but general idea of =~ ...

-------- Original message --------

**Comment by ericoc** [comment]
@dmz006 Can you please give this a shot and let me know if it works for your scenario?

https://github.com/ericoc/zabbix-slack-alertscript/commit/dd9719e533dbf0ccff1e9dc993d02e234b808082

It uses a regular expression in bash and should match multiple different recovery subjects!

**Comment by ericoc** [comment]
merged branch issue13 in to master
