### ISSUE TITLE
Add log to syslog

### ISSUE THREAD

**Issue by ybovard** [ericoc/zabbix-slack-alertscript#19]
For debuging purpose, it would be cool if the script can log to syslog the rc and the message. For exemple:
```
#!/bin/bash

debug=0 #debug value can be 0 (disasbled) or 1 (enabled)
...
curl -m 5 --data-urlencode "${payload}" $url
err=$?
if [ ${debug} -eq 1 ]; then
  logger -t $0 "message sent (rc=$err): ${payload} URL: ${url}"
fi
```

**Comment by ericoc** [comment]
Thanks, but I don't intend to implement debugging in to the script itself. It is simple enough to edit the script to echo to a file temporarily for testing/troubleshooting.
