### ISSUE TITLE
Emoji selection code is breaking.

### ISSUE THREAD

**Issue by singhupendra** [ericoc/zabbix-slack-alertscript#20]
The emoji selection code is breaking and always select the ghost emoji. For me below one is working fine. 

`if [[ "$subject" =~ "OK" ]]; then
	emoji=':smile:'
	color='good'
elif [[ "$subject" =~ "PROBLEM" ]]; then
	emoji=':frowning:'
	color='danger'
else
	emoji=':ghost:'
fi`

**Comment by ericoc** [comment]
Like the README says, the script expects subjects of `PROBLEM` and `RECOVERY` (rather than `OK`):

> Finally, an action can then be created on the "Actions" sub-tab of the "Configuration" tab within the Zabbix servers web interface to notify the Zabbix "Slack" user ensuring that the "Subject" is "PROBLEM" for "Default message" and "RECOVERY" should you choose to send a "Recovery message".
