### ISSUE TITLE
Smiles not send for all statuses.

### ISSUE THREAD

**Issue by itJunky** [ericoc/zabbix-slack-alertscript#21]
First of all i want to say thanks.

May be trouble in slack.

Now when i send alerts with PROBLEM status, in slack channel i see smile :frowning: but when i send alert with OK status, in slack i don't see any smiles...
When i'll added echo output of payload and run script from console, i see inverted shit(OK with smile, PROBLEM without smile) and no smiles for any statuses when send alert from zabbix. Don't understand this magick behavior.

Some interesting thing in sending from command line. When i quoted all params i see smile for status OK, when i don't use quotes around params, it doesn't send smiles, but in echoed payload i don't see any differences. My head is BOOM here.

**Comment by ericoc** [comment]
You're welcome! I'm glad you find this script useful :)

Would you be able to provide a screenshot showing the configuration of your Zabbix media type that executes the `slack.sh` script? It would also be help to see a screenshot of your Zabbix Action configuration that shows the subject names in the problem and recovery messages.

Is it possible to paste command-line output showing the prompt, command executed, and output from running `slack.sh` too?

**Comment by itJunky** [comment]
Actions: http://joxi.ru/82QLNGvU1dWPkm
Now i change it, but it works with smiles like a default template.

Media types: http://joxi.ru/Vm64RDVtxz8BlA
Like in README

And output
```
root@monitoring:~# /etc/zabbix/alert.d/slack.sh '#monitoring' 'OK' 'test_message dfgsd' 
okpayload={"channel": "#monitoring", "username": "Zabbix", "text": "Status: OK! test_message dfgsd", "icon_emoji": ":smile:"}
root@monitoring:~# /etc/zabbix/alert.d/slack.sh '#monitoring' 'PROBLEM' 'test_message dfgsd' 
okpayload={"channel": "#monitoring", "username": "Zabbix", "text": "Status: PROBLEM! test_message dfgsd", "icon_emoji": ":frowning:"}
root@monitoring:~# /etc/zabbix/alert.d/slack.sh '#monitoring' OK test_message dfgsd
okpayload={"channel": "#monitoring", "username": "Zabbix", "text": "Status: OK! test_message", "icon_emoji": ":smile:"}
root@monitoring:~# 

```
and some experiments in slack http://joxi.ru/Q2K1B8vT9dEzBr

**Comment by ericoc** [comment]
Hi,

So the `slack.sh` script was expecting either "PROBLEM" or "RECOVERY" (rather than "PROBLEM" or "OK") as the "subject". I always thought OK was confusing and didn't totally make it clear that something wasn't previously OK, but...

I think this has come up in previous issues so I went ahead and just updated the `slack.sh` script:

https://github.com/ericoc/zabbix-slack-alertscript/commit/3bfb9d908a8d27ebb53b58dae2b79c9286f97a07

The latest version should handle "OK" and "RECOVERY" identically, using a smiling (🙂) emoji.

**Comment by itJunky** [comment]
Yeah, i'm added code lke you, but it doesn't work normally and send smile only for PROBLEM ststus =(
upper i send screenshot with it.

**Comment by ericoc** [comment]
It looks like Slack simply does not attach an emoji to every individual message in their UI. If numerous messages are sent within a short period of time, only the first message in the grouping has an emoji. I see the same thing:

https://imgur.com/a/oShGU

I'm pretty sure this is unavoidable and just the way that Slack formats messages. However, if the messages are separated by some longer amount of time, it seems that Slack formats them differently:

https://imgur.com/a/HgIjE

**Comment by itJunky** [comment]
In my case i heve enough time between messages. But every messages with PROBLEM subject have emoji in slack, and every messages with another subject doesn't have it =(
Looks like bug in slack. Can you confirm this reaction to messages?

And some other thing. When i send message directly cmd trought your script, i have another reaction in slack. I say about it in first message

**Comment by ericoc** [comment]
I really have no idea how Slack decides when to send an emoji or not, but sent them a tweet regarding this GitHub issue:

https://twitter.com/ericohsee/status/913044686461440002

The script is working from my perspective and the display of the emoji in the Slack UI isn't something I have direct control over. The emoji is being sent within the JSON - what Slack decides to do with it visually is up to them.
