### ISSUE TITLE
Script doesn't seem to work on 3.2

### ISSUE THREAD

**Issue by dsgnr** [ericoc/zabbix-slack-alertscript#22]
Hello,
Looking for some help in getting this working. I am running 3.2 and running 
`bash slack.sh '@here' PROBLEM 'Oh no! Something is wrong!'` 
doesn't seem to work. I have filled url='' with my incoming web hook, but unable to test this using the bash command before implementing into Zabbix

**Comment by ericoc** [comment]
Using “@here” is not going to work. This script expects an actual “@username” or “#channel”.
