### ISSUE TITLE
Channel is fixed to one channel

### ISSUE THREAD

**Issue by bitsofinfo** [ericoc/zabbix-slack-alertscript#26]
Webhooks are bound to one destination channel. I don't follow how the configuration in zabbix exposes a field for "channel" but no matter what `#channel` I put in there, it only goes to the one the webhook is for.

**Comment by bitsofinfo** [comment]
i.e. i need to have `slack-channel1.sh` and `slack-channel2.sh`, unless u expose the webhook url as a config option...

**Comment by ericoc** [comment]
You can override the channel which a message is sent to by using the body of the POST request which is sent to the web-hook, as per the example at:

https://api.slack.com/incoming-webhooks#putting_it_all_together

Try it with the script directly, like my README says:

https://github.com/ericoc/zabbix-slack-alertscript#testing

with a command such as

```
$ bash slack.sh '#general' PROBLEM 'Oh no! Something is wrong!'
```

If you can get it to work from the script directly, but it is not working from the Zabbix web UI, you have probably configured your media type or action incorrectly from within the Zabbix web interface.
