### ISSUE TITLE
Curl Error (48)

### ISSUE THREAD

**Issue by voice1** [ericoc/zabbix-slack-alertscript#27]
When deploying this script with the official zabbix docker images, if you deploy the alpine images you will need to install a few additional packages to the zabbix server.

apk add curl curl-dev openssl

You need curl-dev or curl will always return error 48.
Hope that helps anyone with the same issue.

**Comment by ericoc** [comment]
I wouldn’t run zabbix-server in a docker container, but I guess it’s technically possible...
