### ISSUE TITLE
Zabbix not sending alerts!

### ISSUE THREAD

**Issue by bughatti** [ericoc/zabbix-slack-alertscript#31]
Hello and thank you for this script. I am curious if I need to ask for help in here or on the Zabbix forums. I am having the same issue as above. I can walk an alert via command line but zaabbix is not sending anything else. I am currently running Ubuntu 16.04 Desktop. The slack.sh script was originally owned by a different admin user in Zabbix, but I changed it to zabbix with sudo chown zabbix:zabbix /usr/lib/zabbix/alertscripts/slack.sh I also followed the instructions step by step for the media type,user and actions. I have also tried the above to put Defaults:zabbix !requiretty in the visudo file. I create a problem for a device and I get a report on my dashboard saying the device is down but no alert shows up in slack.

Any help would be greatly appreciated!

**Comment by ericoc** [comment]
I have honestly never heard of any one ever running Zabbix on a desktop. In any case, you might want to look at the event details for a specific problem that has occurred to see which actions were triggered by that problem.

For example, here you can see a problem triggering an action which is sending an alert to a Slack `#alerts` channel (via a `reader` Zabbix user account):

![Zabbix problem shown sending Slack alert](https://i.imgur.com/yP3ukun.png)

Additionally, there is no reason for you to be granting `sudo` access to this script at all. This is nearly the equivalent of logging in to your desktop as the `root` user - so do not do this.

**Comment by bughatti** [comment]
So it sounds like I have more steps to go then other than just following your instructions.  I am new to zabbix, I was able to set it all up and pull in templates I need and modify a few things for my dashboard but I have not done anything more with triggers, events or alerts other than what is already in the templates.  So you are saying I need to make sure to build an action off the problems I am monitoring?  I just assumed that with your scripts that anything that popped up under problems would automatically send an alert to Slack, you are saying this is incorrect?

**Comment by ericoc** [comment]
A Zabbix item value can result in a Zabbix trigger occurring. A Zabbix trigger can then result in a Zabbix action. Per the README, you need to actually configure your Zabbix installation to use the script as part of a Zabbix action:

https://github.com/ericoc/zabbix-slack-alertscript#configuration

> Finally, an action can then be created on the "Actions" sub-tab of the "Configuration" tab within the Zabbix servers web interface to notify the Zabbix "Slack" user ensuring that the "Subject" is "PROBLEM" for "Default message" and "RECOVERY" should you choose to send a "Recovery message".

**Comment by bughatti** [comment]
I have a default action setup for Slack, would this action not catch anything with a problem by hostname?

![image](https://user-images.githubusercontent.com/13444378/48982638-3c5aba00-f0f6-11e8-8d01-71393285d2f5.png)

![image](https://user-images.githubusercontent.com/13444378/48982644-4f6d8a00-f0f6-11e8-95fb-d5c3c7c0dc87.png)

**Comment by ericoc** [comment]
You should probably reach out to the Zabbix community via their forum or IRC channel if you're not familiar with setting up Zabbix actions:

https://www.zabbix.com/forum
