### ISSUE TITLE
Sending to the user does not work: channel_not_found 

### ISSUE THREAD

**Issue by itdoginfo** [ericoc/zabbix-slack-alertscript#33]
I try
```
./slack.sh '@user' PROBLEM 'Oh no! Something is wrong!'
```
getting
```
channel_not_found
```

Without the channel everything works
```
payload="payload={\"username\": \"${username//\"/\\\"}\", \"text\": \"${message//\"/\\\"}\", \"icon_emoji\": \"${emoji}\"}"
```
Just in case: Zabbix 4.0.5 in docker

**Comment by ericoc** [comment]
The error message seems pretty clear here:

> channel_not_found

You want to use a "@username" or "#channel" that actually exists for the alerts to go to. If you're using a channel or user name that does exist, but it's still returning `channel_not_found`, then you should reach out to Slack directly.
