### ISSUE TITLE
Emoticons Not Working Properly

### ISSUE THREAD

**Issue by MarkQuilates** [ericoc/zabbix-slack-alertscript#35]
If you have multiple alerts received on the same time or if just 1 minute interval the emoticons not working. Even though you read the message.

But, if there's interval of 5 minutes after the last alerts received it works, able to see the emoticons

**Comment by ericoc** [comment]
This is simply how Slack works: https://github.com/ericoc/zabbix-slack-alertscript/issues/21#issuecomment-332534545

**Comment by MarkQuilates** [comment]
Thanks for that information and swift replied.


Sent from Yahoo Mail for iPhone


On Friday, May 24, 2019, 5:58 PM, ericoc <notifications@github.com> wrote:


Closed #35.
