### ISSUE TITLE
problem notification

### ISSUE THREAD

**Issue by d1mf** [ericoc/zabbix-slack-alertscript#36]
Hello. I see test working, about real-time notification - no. What possible check where problem?

**Comment by ericoc** [comment]
What have you actually done to troubleshoot? Have you followed all of the instructions to set up a trigger and action within the Zabbix web interface per the [README](README):

https://github.com/ericoc/zabbix-slack-alertscript#within-the-zabbix-web-interface

**Comment by d1mf** [comment]
Yes. this my slack account - test working.
![image](https://user-images.githubusercontent.com/10393074/58885304-a332de80-86ea-11e9-84ea-07da19dc8dab.png)

![image](https://user-images.githubusercontent.com/10393074/58885372-bc3b8f80-86ea-11e9-9d36-c6040eeb0d3f.png)
![image](https://user-images.githubusercontent.com/10393074/58885409-ccec0580-86ea-11e9-8236-47024556440d.png)
![image](https://user-images.githubusercontent.com/10393074/58885463-ef7e1e80-86ea-11e9-9d71-0383633b72a3.png)

![image](https://user-images.githubusercontent.com/10393074/58885491-fc027700-86ea-11e9-9048-38f7b5682205.png)

![image](https://user-images.githubusercontent.com/10393074/58885535-12a8ce00-86eb-11e9-83f3-abf503b57bef.png)

![image](https://user-images.githubusercontent.com/10393074/58885562-22281700-86eb-11e9-83a6-cada67521940.png)


![image](https://user-images.githubusercontent.com/10393074/58885656-45eb5d00-86eb-11e9-9130-e7347b0567c2.png)

**Comment by ericoc** [comment]
Is the `slack.sh` script executable (by the zabbix server user) on your server and in your `AlertScriptsPath` directory?

You may need to look at the recent problems in the Zabbix web interface to ensure that the trigger and action are resulting in an attempt to use the Slack media type or for any more detailed error messages. For example, if the `slack.sh` script is not executable by the zabbix server user, you may see an error message like so:

https://i.imgur.com/bAUJaWL.png

This is fixed easily by running `chmod +x slack.sh` to make the script executable.

**Comment by d1mf** [comment]
grep AlertScriptsPath /etc/zabbix/zabbix_server.conf
### Option: AlertScriptsPath                                                                                                       
# AlertScriptsPath=${datadir}/zabbix/alertscripts                                                                                  
AlertScriptsPath=/usr/lib/zabbix/alertscripts       
![image](https://user-images.githubusercontent.com/10393074/58887841-09b9fb80-86ef-11e9-84d8-2c7922142ecc.png)

script executable.  and if I using the test from media types this working

**Comment by d1mf** [comment]
ok. I think the problem there
![image](https://user-images.githubusercontent.com/10393074/58889409-85b54300-86f1-11e9-83c6-02b68d448e72.png)

**Comment by d1mf** [comment]
Note: I fix this problem  switch user for slack
