### ISSUE TITLE
Timeout while executing a shell script.

### ISSUE THREAD

**Issue by emersonramos** [ericoc/zabbix-slack-alertscript#37]
Hi,

I'm trying to use this script for MS Teams notifications and, I don't know why, the notifications is failuring. I follow all instructions and I'm able to execute the script manually.

My script is on /usr/local/share/zabbix/alertscripts and my variable on zabbix-config is AlertScriptsPath=/usr/local/share/zabbix/alertscripts.

ls -la
-rwxrwxrwx 1 zabbix  zabbix  2074 Jun 19 15:38 teams.sh

When I run: ./teams.sh '#Geral' PROBLEM 'Test' it's ok

When it run by zabbix trigger: Timeout while executing a shell script.

I add zabbix ALL=NOPASSWD: ALL on sudoers too.

I need help...

**Comment by ericoc** [comment]
This repository is for sending alerts from Zabbix to Slack. Slack and Microsoft Teams are completely different communication systems. You might want to try:

https://github.com/spasticate/zabbix-MSTeams-alertscript
