### ISSUE TITLE
invalid_payload error when sending alert due to backslashes

### ISSUE THREAD

**Issue by phillip-white-jarden** [ericoc/zabbix-slack-alertscript#38]
Loving this script, so easy and works real well. Thanks for the work!

I do have an issue with certain SNMP alerts. Zabbix agent alerts seem fine.

Server: 4.2.1
Host: Windows 2012
Item: SNMPv2

Error:
![image](https://user-images.githubusercontent.com/51097800/64386787-1e12e900-d08e-11e9-8ce7-a6c6ab326eb3.png)

I have followed the install steps, apart from creating a Slack user. I have just assigned the Slack media type to the admin user, and under actions it only sends to the admin user.

Actions configured as follows: (All default Zabbix)
Operations Default message:
```
Problem has been resolved at {EVENT.RECOVERY.TIME} on {EVENT.RECOVERY.DATE}
Problem name: {EVENT.NAME}
Host: {HOST.NAME}
Severity: {EVENT.SEVERITY}

Original problem ID: {EVENT.ID}
{TRIGGER.URL}
```

Recovery operations Default message:
```
Problem has been resolved at {EVENT.RECOVERY.TIME} on {EVENT.RECOVERY.DATE}
Problem name: {EVENT.NAME}
Host: {HOST.NAME}
Severity: {EVENT.SEVERITY}

Original problem ID: {EVENT.ID}
```

Ipdate operations Dewfault message
```
{USER.FULLNAME} {EVENT.UPDATE.ACTION} problem at {EVENT.UPDATE.DATE} {EVENT.UPDATE.TIME}.
{EVENT.UPDATE.MESSAGE}

Current problem status is {EVENT.STATUS}, acknowledged: {EVENT.ACK.STATUS}.
```

I don't think it has anything to do with the Actions.

Any advise on how to fix or debug?

**Comment by ericoc** [comment]
I can't see what your Zabbix server is sending to the Slack.com webhook URL, but the "invalid_payload" response is definitely from Slack.com - all I can really recommend is that you edit slack.sh locally to debug further. Maybe have it write out your POST data to a file and/or run curl with -vvv and pipe both stdout and stderr to a file to troubleshoot.

**Comment by phillip-white-jarden** [comment]
Managed to find the error by editing the script locally.

```
# Get the user/channel ($1), subject ($2), and message ($3)
to="#zabbix-alerts"
subject="Problem: test"
message="J:\ This won't work"
```

It's an issue with the `\` character.

Slack does accept `\` in webhooks. Anyway we can fix the script to work with this?

**Comment by ericoc** [comment]
I really don't know what the right answer is since the construction of the payload variable in the script is already an absolute disaster to look at... it was designed to allow quotation marks in the alert subject and/or message:

```
# Build JSON payload which will be HTTP POST'ed to the Slack.com web-hook URL
payload="payload={\"channel\": \"${to//\"/\\\"}\",  \
\"username\": \"${username//\"/\\\"}\", \
\"attachments\": [{\"fallback\": \"${subject//\"/\\\"}\", \"title\": \"${subject//\"/\\\"}\", \"text\": \"${message//\"/\\\"}\", \"color\": \"${color}\"}], \
\"icon_emoji\": \"${emoji}\"}"
```

If you can make the script allow quotes, apostrophes, and backslashes (and whatever other common characters that may or may not come up in an alerts subject and message), then feel free to submit a PR and I'd be happy to test it and merge it. I've tried a few things in the past couple hours without any success.

A backslash should be escaped with a backslash( i.e. `\\` becomes `\`), but I'm not particularly interested in calling out to sed and/or awk, etc. everywhere to try to mangle text... I honestly am really dissatisfied with how the payload variable is currently built.

**Comment by phillip-white-jarden** [comment]
Seems easier to exclude it. I found a somewhat more basic payload in one the forks, and changed it to `${message//'\'}` to exclude the backslash.

Payload is now:

```
payload="payload={
        \"channel\": \"${to}\",
        \"username\": \"${username}\",
        \"icon_emoji\": \"${emoji}\",
        \"attachments\": [
           {
                \"title\": \"${subject}\",
                \"fallback\": \"${subject}\",
                \"text\": \"${message//'\'}\",
                \"color\": \"${color}\",
           }
        ] }"
```

With Action message as:
```
Problem started at {EVENT.TIME} on {EVENT.DATE}
Problem name: {EVENT.NAME}
Host: {HOST.NAME}
Severity: {EVENT.SEVERITY}

Original problem ID: {EVENT.ID}
{TRIGGER.URL}
<https://zabbix.server.com/zabbix.php?action=problem.view&filter_triggerids%5B%5D={TRIGGER.ID}&filter_set=1|Go to Problem>
```

It works quite well:

![image](https://user-images.githubusercontent.com/51097800/64401617-c3957f00-d0c5-11e9-95c4-a6dd19cc80ce.png)

**Comment by ericoc** [comment]
I'm glad that that works for you! That fork is an earlier version of the script. The older version is prior to the untidy solution that was added to try to escape quotation marks. The only downside is that any alerts that have a quotation mark in the subject or message fields could cause a failure similar to what you were seeing before...

**Comment by phillip-white-jarden** [comment]
I ran into this issue again today, and found the `"` character was an issue. Tried to play around with string manipulation to remove both `\` and `"` but couldn't get the right syntax. Was easier to do this with sed:

```
subject=$(echo $2 | sed "s/[\]//g")
message=$(echo $3 | sed "s/[\]//g")
```

Script is now:

```
#!/bin/bash

# Slack incoming web-hook URL and user name
url='<url>'      # example: url='https://hooks.slack.com/services/QW3R7Y/D34DC0D3/BCADFGabcDEF123'
username='Zabbix'

## Values received by this script:
# To = $1 / Slack channel or user to send the message to, specified in the Zabbix web interface; "@username" or "#channel"
# Subject = $2 / subject of the message sent by Zabbix; by default, it is usually something like "(Problem|Resolved): Lack of free swap space on Zabbix server"
# Message = $3 / message body sent by Zabbix; by default, it is usually approximately 4 lines detailing the specific trigger involved
# Alternate URL = $4 (optional) / alternative Slack.com web-hook URL to replace the above hard-coded one; useful when multiple groups have seperate Slack teams
# Proxy = $5 (optional) / proxy host including port (such as "example.com:8080")

# Get the user/channel ($1), subject ($2), and message ($3)
to="$1"
subject=$(echo $2 | sed "s/[\]//g")
message=$(echo $3 | sed "s/[\]//g")

# Change message emoji and notification color depending on the subject indicating whether it is a trigger going in to problem state or recovering
recoversub='^RECOVER(Y|ED)?$|^OK$|^Resolved.*'
problemsub='^PROBLEM.*|^Problem.*'

if [[ "$subject" =~ $recoversub ]]; then
    emoji=':sunglasses:'
    color='#43de35'
elif [[ "$subject" =~ $problemsub ]]; then
    emoji=':scream:'
    color='#c21010'
else
    emoji=':zabbix:'
    color='#CCCCCC'
fi

# Replace the above hard-coded Slack.com web-hook URL entirely, if one was passed via the optional 4th parameter
url=${4-$url}

# Use optional 5th parameter as proxy server for curl
proxy=${5-""}
if [[ "$proxy" != '' ]]; then
    proxy="-x $proxy"
fi

# Build JSON payload which will be HTTP POST'ed to the Slack.com web-hook URL
payload="payload={\"channel\": \"${to//\"/\\\"}\",  \
\"username\": \"${username//\"/\\\"}\", \
\"attachments\": [{\"fallback\": \"${subject//\"/\\\"}\", \"title\": \"${subject//\"/\\\"}\", \"text\": \"${message//\"/\\\"}\", \"color\": \"${color}\"}], \
\"icon_emoji\": \"${emoji}\"}"

# Execute the HTTP POST request of the payload to Slack via curl, storing stdout (the response body)
return=$(curl $proxy -sm 5 --data-urlencode "${payload}" $url -A 'zabbix-slack-alertscript / https://github.com/ericoc/zabbix-slack-alertscript')

# If the response body was not what was expected from Slack ("ok"), something went wrong so print the Slack error to stderr and exit with non-zero
if [[ "$return" != 'ok' ]]; then
    >&2 echo "$return"
    exit 1
fi
```

**Comment by ericoc** [comment]
The latest version of Zabbix (4.4) has included its own webhook functionality:

https://github.com/ericoc/zabbix-slack-alertscript#44
https://www.zabbix.com/documentation/4.4/manual/config/notifications/media/webhook
