### ISSUE TITLE
Send Message to "@channel"

### ISSUE THREAD

**Issue by aryelnr** [ericoc/zabbix-slack-alertscript#7]
Hello.
I configured integration, but have a huge need to send messages to #xpto_channel and then alert all members with @channel.    

I tried to enter the the channel in the message, but it is presented as text, not as a call to the entire channel.

You can implement this function?

Thanks in advance
![capturar](https://cloud.githubusercontent.com/assets/13068214/9414742/3198efc4-4811-11e5-9fa3-f8b7d8d5bb0a.PNG)

**Comment by ericoc** [comment]
Hi,

You can highlight everyone in the channel that you send the message to using the following text inside of your message:

    <!channel>

which should expand to "@channel" and highlight everyone, per the following Slack documentation:

https://api.slack.com/docs/formatting

Cheers,
Eric
