### ISSUE TITLE
Alert Script Parameters in Zabbix 3.0

### ISSUE THREAD

**Issue by lunchables** [ericoc/zabbix-slack-alertscript#9]
In Zabbix 3.0 you have to configure the Media Type to pass the parameters manually, they are not passed automatically as $1, $2 and $3 anymore.  

You need to add three parameters to the Media Type manually:
{ALERT.SENDTO}
{ALERT.SUBJECT}
{ALERT.MESSAGE}

You might want to update your documentation to reflect this change in Zabbix 3.0.  Reference here:
https://www.zabbix.com/documentation/3.0/manual/config/notifications/media/script

**Comment by tkdywc** [comment]
Dear lunchables,

It doesn't work for me, do you know why?
![screen shot 2016-04-05 at 2 51 02 pm](https://cloud.githubusercontent.com/assets/17143558/14273515/e4912e40-fb3d-11e5-89d6-668f6632cf71.png)

BR,

Yung

**Comment by lunchables** [comment]
Did the script work when you ran it manually from the command line?

**Comment by tkdywc** [comment]
Yes! I use it at zabbix2.4, command line is working in zabbix3.0.1 as well. Without the Macro, an empty message with semicolon, with marco, no message will be revived completely... Would you share more on how you make it work? I did follow all steps on the readme and reference zabbix doc. Thanks

**Comment by mw-dts** [comment]
Hi Eric,

Apologies for posting on a closed ticket but I am still getting this same issue Zabbix 3.0.3 (centos7). 

I generated incoming webhook for private and added media type to my user with correct send to. All the parameters are set exactly as described
![slack](https://cloud.githubusercontent.com/assets/19587055/16040304/b6f0da1a-3226-11e6-8f13-fca34fab2fa5.JPG) I verified the webhook was correct and am able to send using bash.

I thought maybe the privatechannel doesn't work so I then created a #zabbix channel and new webhook. This also didn't work but can succesfully send from command line.

AlertScriptsPath = /usr/lib/zabbix/alertscripts and I have verified permissions. I have restarted zabbix server and created new action just for slack (previously all media) but have run out of ideas. Any and all suggestions are welcome.

**Comment by ericoc** [comment]
You might need to double-check that the user that `zabbix_server` is running as has the ability to execute the `slack.sh` script (`chmod +x`). Additionally, you can check out "Monitoring" tab -> "Events" sub-tab in the Zabbix web interface for specific triggered events that you believe should be kicking off the action and subsequent alert to troubleshoot further.

**Comment by mw-dts** [comment]
Perms are 755 for everything under /usr/lib/

-rwxr-xr-x  1 root root 1.5K Jun 14 11:13 slack.sh

I created a simple trigger vfs.file.exists[/tmp/test.txt].last(0)}=0 which sends a problem email through fine when I remove the file and recovery when I create it.

**Comment by mw-dts** [comment]
i have just thought! The servers are behind a proxy and so for bash command we would run 

export https_proxy=https://proxyaddress

Would I need to add something to the script or should it pick up the proxy settings?

**Comment by ericoc** [comment]
If you're required to use a proxy server for outbound HTTP(S) connections, you can modify the `slack.sh` script `curl` command to include `-x https://proxyaddress/` like so:

    curl -x https://proxy -m 5 --data-urlencode "${payload}" $url -A 'zabbix-slack-alertscript / https://github.com/ericoc/zabbix-slack-alertscript'

**Comment by mw-dts** [comment]
Damn, I thought I was onto something as when running from bash I got
curl: (56) Proxy CONNECT aborted due to timeout

Modified to "-m 8" and that seemed to work from bash but it is still doing nothing when going through Zabbix. I am going to turn debugging up and see if I can find anything

**Comment by mw-dts** [comment]
Thanks for your help, it was the proxy setting! It needed -x http://proxy:port -m 8

**Comment by blairbeveridge** [comment]
Hi ericoc, sorry for commenting on an old thread.

We have Zabbix 3.2 and have this script installed.  We can call it from the CLI and it works properly but cannot get zabbix to call it.  We have tried setting it up as mentioned in your article but have not been able to get it to work.  I believe it is in our action call.  I have tried it as part of our pre-existing email action as well as on it's own.  Neither have worked to this point.  Hope you can shed some light.  

![zabslack](https://cloud.githubusercontent.com/assets/22846734/19404258/9fa0eb6a-923a-11e6-868a-28b1d843de91.PNG)

**Comment by ericoc** [comment]
@blairbeveridge I'm not sure what to tell you, but you might need to make sure the script is executable (0755), otherwise you might want to check out the Zabbix documentation (https://www.zabbix.com/documentation/3.0/manual/config/notifications/action) or their forums (https://www.zabbix.com/forum/forumdisplay.php?f=6).

**Comment by andrewkendall** [comment]
@blairbeveridge I'm seeing the exact same problem since upgrading to 3.2. Did you find a solution?

**Comment by ericoc** [comment]
@blairbeveridge @andrewkendall Browsing through the "Events" sub-tab of the "Monitoring" tab in the Zabbix web UI might reveal some extra troubleshooting information. You can click the timestamp of an event (assuming your triggers are actually triggering) and the "Message actions" section should give more information on what actions resulted from the trigger.

**Comment by andrewkendall** [comment]
Thank you @ericoc. Since your reply I've found the answer for my issue. It was incredibly simple, it looks like something with the upgrade to 3.2 had disabled alerts so all I needed to do was re-enable them via the web interface:

![2fe5add2-b20f-4628-bd42-50d63a510a0b](https://cloud.githubusercontent.com/assets/11718/19621518/949e561a-988b-11e6-969c-c421e3f2020d.png)

**Comment by irom77** [comment]
I fell into the similar issue in _Zabbix 3.2.3_ ,  **slack.sh** works juts fine when run from bash but not alerting in zabbix (alerts are enabled;) I ran out of ideas
```
docker exec zabbix ls -l /usr/local/share/zabbix/alertscripts
total 4
-rwxrwxr-x. 1 1003 1003 1587 Dec 30 14:06 slack.sh
```

**Comment by hamiltonfvi** [comment]
Thanks a lot, so that was the reason my script wasnt working properly.
